name: zamgławiacz c150+
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56394
title: Zamgławiacz  - aktywna mgła odkaża pokój 25m2 w czasie poniżej minuty
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72968151-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2c3bd'
    - '#707070'
    - '#969a99'
    - '#040605'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.03758425638079643
  rhythmicContrast: 0.75
purpose: []
