name: zamgławiacz c150+
favicon: null
layout_spectrum: 0.06958480481989682
typography_spectrum: 0.5573315108194947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0606171190738678
  lightness: 0.6437458174768835
  saturation: 0.03758425638079643
  rhythmicContrast: 0.9226392884738743
purpose: []
